### ISSUE TITLE
macOS hardcoded to homebrew version

### ISSUE THREAD

**Issue by craigmac** [nvim-telescope/telescope-smart-history.nvim#3]
Found this out through stack trace when I couldn't connect to my `vim.fn.stdpath("data") .. databases/telescope_history.sqlite3` file. My `which sqlite3` points to `/usr/bin/sqlite3` which is version `3.32.3`. Can it not use this sqlite3?

**Comment by fourstepper** [comment]
could you share what issue that caused and how you solved it?

thanks

**Comment by Conni2461** [comment]
sqlite.lua does not use the `sqlite3` binary. It uses the sqlite3 shared lib and uses bindings into the c library

Do you have this problem? https://github.com/tami5/sqlite.lua/issues/134#issuecomment-1089804432

**Comment by craigmac** [comment]
Sorry, I don’t remember at this point, but I believe it was an error on my part.
